source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'BestYou' do

  pod 'GPUImage'
  pod 'Masonry' 
  pod 'Toast', '~> 4.0.0'
  pod 'SVProgressHUD'
  pod 'TZImagePickerController'

end
